version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  wordpress:
    build: ./wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      -  db_data:/var/lib/mysql
    restart: always
    networks:
      - network
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    
networks:
  network:
    driver: bridge

volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: ~/home/dlanzilo/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/home/dlanzilo/data/wordpress
      o: bind